# Generated by Django 6.0.3 on 2026-03-31 19:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='banners/')),
                ('image_mobile', models.ImageField(blank=True, help_text='Mobile version of banner', null=True, upload_to='banners/')),
                ('link', models.URLField(blank=True, null=True)),
                ('link_text', models.CharField(default='Shop Now', max_length=100)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('position', models.CharField(choices=[('hero', 'Hero Banner'), ('top', 'Top Bar'), ('middle', 'Middle Section'), ('bottom', 'Bottom Section'), ('sidebar', 'Sidebar'), ('popup', 'Popup')], default='hero', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('background_color', models.CharField(blank=True, max_length=7, null=True)),
                ('text_color', models.CharField(blank=True, max_length=7, null=True)),
                ('button_color', models.CharField(blank=True, max_length=7, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', 'display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('products', 'Products Page'), ('about', 'About Page'), ('contact', 'Contact Page'), ('faq', 'FAQ Page'), ('terms', 'Terms & Conditions'), ('privacy', 'Privacy Policy'), ('shipping', 'Shipping Info'), ('returns', 'Returns Policy')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('keywords', models.CharField(blank=True, max_length=500, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('robots_meta', models.CharField(default='index, follow', help_text="e.g., 'index, follow' or 'noindex, nofollow'", max_length=100)),
                ('structured_data', models.JSONField(blank=True, default=dict, help_text='JSON-LD structured data')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Setting',
                'verbose_name_plural': 'SEO Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(default='Gadgets Store', max_length=100)),
                ('site_tagline', models.CharField(default='Your One-Stop Shop for Gadgets & Accessories', max_length=255)),
                ('site_description', models.TextField(blank=True, help_text='Short description for SEO', null=True)),
                ('contact_email', models.EmailField(default='support@gadgetsstore.com', max_length=254)),
                ('contact_phone', models.CharField(default='+2348012345678', max_length=17)),
                ('contact_phone_secondary', models.CharField(blank=True, max_length=17, null=True)),
                ('whatsapp_number', models.CharField(default='+2348012345678', max_length=17)),
                ('business_address', models.TextField(blank=True, null=True)),
                ('business_hours', models.CharField(default='Mon - Sat: 9:00 AM - 6:00 PM', max_length=255)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('default_currency', models.CharField(default='₦', max_length=10)),
                ('currency_code', models.CharField(default='NGN', max_length=10)),
                ('currency_position', models.CharField(choices=[('before', 'Before Amount'), ('after', 'After Amount')], default='before', max_length=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=50000, max_digits=12)),
                ('flat_shipping_rate', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Tax rate as percentage', max_digits=5)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('logo_dark', models.ImageField(blank=True, help_text='Logo for dark mode', null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('primary_color', models.CharField(default='#2563eb', max_length=7)),
                ('secondary_color', models.CharField(default='#1e40af', max_length=7)),
                ('accent_color', models.CharField(default='#f59e0b', max_length=7)),
                ('enable_reviews', models.BooleanField(default=True)),
                ('enable_wishlist', models.BooleanField(default=True)),
                ('enable_compare', models.BooleanField(default=True)),
                ('enable_guest_checkout', models.BooleanField(default=True)),
                ('enable_newsletter', models.BooleanField(default=True)),
                ('enable_live_chat', models.BooleanField(default=True)),
                ('enable_whatsapp', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True, default="We're currently performing maintenance. Please check back soon.", null=True)),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_title', models.CharField(blank=True, help_text="e.g., 'Verified Buyer' or 'Loyal Customer'", max_length=255, null=True)),
                ('customer_image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('content', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', 'display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(help_text='FontAwesome icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('import', 'Import'), ('other', 'Other')], max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page', models.CharField(choices=[('about', 'About Us'), ('terms', 'Terms & Conditions'), ('privacy', 'Privacy Policy'), ('shipping', 'Shipping Information'), ('returns', 'Returns & Refunds'), ('faq', 'FAQ'), ('careers', 'Careers')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['page'],
            },
        ),
    ]
