# Generated by Django 5.2.12 on 2026-03-31 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=100)),
                ('routing_number', models.CharField(blank=True, max_length=100)),
                ('swift_code', models.CharField(blank=True, max_length=50)),
                ('bank_address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Bank Details',
                'ordering': ['display_order', 'bank_name'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('order_confirmation', 'Order Confirmation'), ('payment_received', 'Payment Received'), ('payment_verified', 'Payment Verified'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('welcome', 'Welcome Email'), ('password_reset', 'Password Reset')], max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body_html', models.TextField()),
                ('body_text', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6B7280', help_text='Hex color code for status badge', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Order Statuses',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Chris-Lux', max_length=255)),
                ('site_tagline', models.CharField(default='Premium Hair Extensions & Wigs', max_length=255)),
                ('site_description', models.TextField(blank=True, help_text='Meta description for SEO')),
                ('site_keywords', models.CharField(blank=True, help_text='Meta keywords for SEO (comma separated)', max_length=500)),
                ('logo', models.ImageField(blank=True, help_text='Site logo', null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, help_text='Site favicon', null=True, upload_to='site/')),
                ('contact_email', models.EmailField(default='support@chris-lux.com', max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('business_address', models.TextField(blank=True)),
                ('business_city', models.CharField(blank=True, max_length=100)),
                ('business_country', models.CharField(blank=True, max_length=100)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('pinterest_url', models.URLField(blank=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('NGN', 'Nigerian Naira (₦)')], default='USD', max_length=3)),
                ('currency_symbol', models.CharField(default='$', max_length=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Tax rate percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order for free shipping (0 to disable)', max_digits=10)),
                ('standard_shipping_cost', models.DecimalField(decimal_places=2, default=15.0, max_digits=10)),
                ('express_shipping_cost', models.DecimalField(decimal_places=2, default=25.0, max_digits=10)),
                ('overnight_shipping_cost', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('order_prefix', models.CharField(default='CL', max_length=10)),
                ('auto_cancel_hours', models.PositiveIntegerField(default=48, help_text='Hours after which pending orders are auto-cancelled')),
                ('admin_notification_email', models.EmailField(blank=True, help_text='Email to receive admin notifications', max_length=254)),
                ('notify_on_new_order', models.BooleanField(default=True)),
                ('notify_on_payment', models.BooleanField(default=True)),
                ('notify_on_low_stock', models.BooleanField(default=True)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('primary_color', models.CharField(default='#6B21A8', max_length=7)),
                ('secondary_color', models.CharField(default='#1F2937', max_length=7)),
                ('accent_color', models.CharField(default='#F59E0B', max_length=7)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True, default='We are currently performing maintenance. Please check back soon.')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
