# Generated by Django 5.2.15 on 2026-06-10 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('executives', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Election',
                'verbose_name_plural': 'Elections',
                'db_table': 'elections_election',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='elections_e_status_e3ccd0_idx'), models.Index(fields=['start_date'], name='elections_e_start_d_84de8e_idx')],
            },
        ),
        migrations.CreateModel(
            name='HandoverLedger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bank_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Bank Balance')),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Cash Balance')),
                ('assets_description', models.TextField(blank=True, verbose_name='Assets Description')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers', to='executives.executive', verbose_name='Outgoing Executive')),
            ],
            options={
                'verbose_name': 'Handover Ledger',
                'verbose_name_plural': 'Handover Ledgers',
                'db_table': 'elections_handoverledger',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('post', models.CharField(max_length=50, verbose_name='Post')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='elections/candidates/%Y/%m/', verbose_name='Campaign Photo')),
                ('manifesto', models.TextField(blank=True, verbose_name='Manifesto')),
                ('votes', models.PositiveIntegerField(default=0, verbose_name='Votes')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidacies', to='members.member', verbose_name='Member')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.election', verbose_name='Election')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'db_table': 'elections_candidate',
                'ordering': ['-votes', 'post'],
                'unique_together': {('election', 'member', 'post')},
            },
        ),
    ]
